### ISSUE TITLE
About the problem that the parameters in the loaded pretraining model are inconsistent with those in the initialization model  

### ISSUE THREAD

**Issue by SerendipityCreate** [bl-2633/GAT-GO#1]
1. The parameters of the pre-training model are as follows:  'check_point['state_dict'].keys()'
odict_keys(['esm_in.0.weight', 'esm_in.0.bias', 'seq_in.0.weight', 'seq_in.0.bias', 'pssm_in.0.weight', 'pssm_in.0.bias', 'full1d_in.0.weight', 'full1d_in.0.bias', 'classifier.0.weight', 'classifier.0.bias', 'classifier.2.weight', 'classifier.2.bias', 'gc1.att_l', 'gc1.att_r', 'gc1.lin_l.weight', 'gc1.lin_r.weight', 'gc2.att_l', 'gc2.att_r', 'gc2.lin_l.weight', 'gc2.lin_r.weight', 'gc3.att_l', 'gc3.att_r', 'gc3.lin_l.weight', 'gc3.lin_r.weight', 'gc4.att_l', 'gc4.att_r', 'gc4.lin_l.weight', 'gc4.lin_r.weight', 'gp1.gnn.lin_l.weight', 'gp1.gnn.lin_l.bias', 'gp1.gnn.lin_r.weight', 'gp2.gnn.lin_l.weight', 'gp2.gnn.lin_l.bias', 'gp2.gnn.lin_r.weight', 'gp3.gnn.lin_l.weight', 'gp3.gnn.lin_l.bias', 'gp3.gnn.lin_r.weight', 'gp4.gnn.lin_l.weight', 'gp4.gnn.lin_l.bias', 'gp4.gnn.lin_r.weight'])

2. However, the parameters for initializing the model are as follows:
gc1.att_src : torch.Size([1, 12, 512])
gc1.att_dst : torch.Size([1, 12, 512])
gc1.lin_src.weight : torch.Size([6144, 512])
gc2.att_src : torch.Size([1, 12, 512])
gc2.att_dst : torch.Size([1, 12, 512])
gc2.lin_src.weight : torch.Size([6144, 512])
gc3.att_src : torch.Size([1, 12, 1024])
gc3.att_dst : torch.Size([1, 12, 1024])
gc3.lin_src.weight : torch.Size([12288, 512])
gc4.att_src : torch.Size([1, 12, 1024])
gc4.att_dst : torch.Size([1, 12, 1024])
gc4.lin_src.weight : torch.Size([12288, 1024])
gp1.gnn.lin_rel.weight : torch.Size([1, 512])
gp1.gnn.lin_rel.bias : torch.Size([1])
gp1.gnn.lin_root.weight : torch.Size([1, 512])
gp2.gnn.lin_rel.weight : torch.Size([1, 512])
gp2.gnn.lin_rel.bias : torch.Size([1])
gp2.gnn.lin_root.weight : torch.Size([1, 512])
gp3.gnn.lin_rel.weight : torch.Size([1, 1024])
gp3.gnn.lin_rel.bias : torch.Size([1])
gp3.gnn.lin_root.weight : torch.Size([1, 1024])
gp4.gnn.lin_rel.weight : torch.Size([1, 1024])
gp4.gnn.lin_rel.bias : torch.Size([1])
gp4.gnn.lin_root.weight : torch.Size([1, 1024])

This caused me to fail to load the pre-training model, so what might the problem.

**Comment by bl-2633** [comment]
can your show the error message when you try to load the model?

**Comment by SerendipityCreate** [comment]
Traceback (most recent call last):
  File "GAT-GO.py", line 62, in <module>
    model.load_state_dict(check_point['state_dict'], strict = True)
  File "/opt/conda/envs/GAT-GO/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1468, in load_state_dict
    load(self)
  File "/opt/conda/envs/GAT-GO/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1466, in load
    load(child, prefix + name + '.')
  File "/opt/conda/envs/GAT-GO/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1466, in load
    load(child, prefix + name + '.')
  File "/opt/conda/envs/GAT-GO/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1462, in load
    module._load_from_state_dict(
  File "/opt/conda/envs/GAT-GO/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1372, in _load_from_state_dict
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
  File "/opt/conda/envs/GAT-GO/lib/python3.8/site-packages/torch_geometric/nn/dense/linear.py", line 131, in _lazy_load_hook
    weight = state_dict[prefix + 'weight']
KeyError: 'gc1.lin_src.weight'

**Comment by bl-2633** [comment]
What's your torch_geometric version?

**Comment by SerendipityCreate** [comment]
py38_torch_1.10.0_cu113

**Comment by bl-2633** [comment]
Can you try to use torch_geometric-1.7.0?

**Comment by bl-2633** [comment]
> Can you try to use torch_geometric-1.7.0?

along with torch-1.7.1, torch_cluster-1.5.8, torch_scatter-2.0.5, torch_sparse-0.6.8, torch_spline_conv-1.2.1

Since torch_geometric was under rapid development when this package was written, many features are not backward compatible.

**Comment by SerendipityCreate** [comment]
ok，I will make a try.



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 4, 2022 12:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bl-2633/GAT-GO] About the problem that the parameters in the loaded pretraining model are inconsistent with those in the initialization model   (Issue #1)




  
Can you try to use torch_geometric-1.7.0?
  
along with torch-1.7.1, torch_cluster-1.5.8, torch_scatter-2.0.5, torch_sparse-0.6.8, torch_spline_conv-1.2.1
 
Since torch_geometric was under rapid development when this package was written, many features are not backward compatible.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
