### ISSUE TITLE
onehot encode

### ISSUE THREAD

**Issue by ytao20** [bl-2633/GAT-GO#4]
How is the onehot encoding of PDB chain mapped? What is the order of 25 characters?

**Comment by bl-2633** [comment]
Hi here is the mapping of AA identity to the index in the one-hot encoded primary sequence
 alphabet = {
     'A': 0,
     'B': 1,
     'C': 2,
     'D': 3,
     'E': 4,
     'F': 5,
     'G': 6,
     'H': 7,
     'I': 8,
     'K': 9,
     'L': 10,
     'M': 11,
     'N': 12,
     'O': 13,
     'P': 14,
     'Q': 15,
     'R': 16,
     'S': 17,
     'T': 18,
     'U': 19,
     'V': 20,
     'W': 21,
     'X': 22,
     'Y': 23,
     'Z': 24
    }
