### ISSUE TITLE
Dataset link

### ISSUE THREAD

**Issue by Worldseer** [bl-2633/GAT-GO#5]
1

**Comment by Worldseer** [comment]
> Can you provide the PDBmmseq train and test dataset used in the article?

**Comment by Worldseer** [comment]
Exceeded download quota, unable to download

**Comment by bl-2633** [comment]
I just checked the link, and it's working fine, can you try again? If you still have issues using the link, send me an email, and I will share another link with you.

**Comment by Worldseer** [comment]
Thanks, I've already downloaded it
