### ISSUE TITLE
Structural model from AlphaFold2 as input?

### ISSUE THREAD

**Issue by BinhongLiu** [bl-2633/GAT-GO#7]
Hi,
     I'm wondering if the GAT-GO could take structural model from AlphaFold2 as input for the function prediction.

**Comment by bl-2633** [comment]
Yes, you will need to extract the inter-residue contact map from the AF2 predicted structures and match the input format along with the PLM embeddings.

**Comment by BinhongLiu** [comment]
Great! Thanks for your reply and kind help! I just also send my issues to you via email.
I'll try to find some tools to extract the inter-residue contact map from the AF2 predicted structures. Besides, I'd like to know how to prepare the .pt file storing processed features from a sequence.  
Thank you!
